### ISSUE TITLE
Only the original thread that created a view hierarchy can touch its views on resumeCameraPreview

### ISSUE THREAD

**Issue by jordanbisato** [m1ga/hyperloop.barcode#2]
In resume method when i call the resumeCameraPreview, with run-on-main-thread = false in tiapp.xml (APPCELERATOR) i get this error, the camera permissions is checked. Why i get this error, someone can help me?

**The full log:**
CameraPreview: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
[ERROR] CameraPreview: android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
[ERROR] CameraPreview: 	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:6430)
[ERROR] CameraPreview: 	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:879)
[ERROR] CameraPreview: 	at android.view.View.requestLayout(View.java:16683)
[ERROR] CameraPreview: 	at android.view.View.requestLayout(View.java:16683)
[ERROR] CameraPreview: 	at android.view.View.requestLayout(View.java:16683)
[ERROR] CameraPreview: 	at android.view.View.requestLayout(View.java:16683)
[ERROR] CameraPreview: 	at android.view.View.requestLayout(View.java:16683)
[ERROR] CameraPreview: 	at android.view.View.requestLayout(View.java:16683)
[ERROR] CameraPreview: 	at android.view.View.requestLayout(View.java:16683)
[ERROR] CameraPreview: 	at android.view.View.requestLayout(View.java:16683)
[ERROR] CameraPreview: 	at android.support.v4.widget.DrawerLayout.requestLayout(DrawerLayout.java:1244)
[ERROR] CameraPreview: 	at android.view.View.requestLayout(View.java:16683)
[ERROR] CameraPreview: 	at android.widget.RelativeLayout.requestLayout(RelativeLayout.java:352)
[ERROR] CameraPreview: 	at android.view.View.requestLayout(View.java:16683)
[ERROR] CameraPreview: 	at android.view.View.requestLayout(View.java:16683)
[ERROR] CameraPreview: 	at android.view.View.requestLayout(View.java:16683)
[ERROR] CameraPreview: 	at android.view.View.requestLayout(View.java:16683)
[ERROR] CameraPreview: 	at android.view.View.requestLayout(View.java:16683)
[ERROR] CameraPreview: 	at android.view.View.requestLayout(View.java:16683)
[ERROR] CameraPreview: 	at android.view.View.requestLayout(View.java:16683)
[ERROR] CameraPreview: 	at android.view.View.setLayoutParams(View.java:10725)
[ERROR] CameraPreview: 	at me.dm7.barcodescanner.core.CameraPreview.setViewSize(CameraPreview.java:186)
[ERROR] CameraPreview: 	at me.dm7.barcodescanner.core.CameraPreview.adjustViewSize(CameraPreview.java:138)
[ERROR] CameraPreview: 	at me.dm7.barcodescanner.core.CameraPreview.setupCameraParameters(CameraPreview.java:129)
[ERROR] CameraPreview: 	at me.dm7.barcodescanner.core.CameraPreview.showCameraPreview(CameraPreview.java:82)
[ERROR] CameraPreview: 	at me.dm7.barcodescanner.core.BarcodeScannerView.resumeCameraPreview(BarcodeScannerView.java:121)
**[ERROR] CameraPreview: 	at me.dm7.barcodescanner.zxing.ZXingScannerView.resumeCameraPreview(ZXingScannerView.java:181)**
[ERROR] CameraPreview: 	at java.lang.reflect.Method.invokeNative(Native Method)
[ERROR] CameraPreview: 	at java.lang.reflect.Method.invoke(Method.java:515)
[ERROR] CameraPreview: 	at hyperloop.BaseProxy.invokeMethod(BaseProxy.java:157)
[ERROR] CameraPreview: 	at hyperloop.InstanceProxy.invokeMethod(InstanceProxy.java:184)
[ERROR] CameraPreview: 	at hyperloop.BaseProxy.callNativeFunction(BaseProxy.java:129)
[ERROR] CameraPreview: 	at org.appcelerator.kroll.runtime.v8.V8Object.nativeFireEvent(Native Method)
[ERROR] CameraPreview: 	at org.appcelerator.kroll.runtime.v8.V8Object.fireEvent(V8Object.java:62)
[ERROR] CameraPreview: 	at org.appcelerator.kroll.KrollProxy.doFireEvent(KrollProxy.java:934)
[ERROR] CameraPreview: 	at org.appcelerator.kroll.KrollProxy.handleMessage(KrollProxy.java:1157)
[ERROR] CameraPreview: 	at org.appcelerator.titanium.proxy.TiViewProxy.handleMessage(TiViewProxy.java:363)
[ERROR] CameraPreview: 	at android.os.Handler.dispatchMessage(Handler.java:98)
[ERROR] CameraPreview: 	at android.os.Looper.loop(Looper.java:136)
[ERROR] CameraPreview: 	at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:118)
[ERROR] ViewRootImpl: sendUserActionEvent() mView == null

**Comment by jordanbisato** [comment]
To fix, i set the `<property name="run-on-main-thread" type="bool">true</property>` to true in tiapp.xml

**Comment by jordanbisato** [comment]
If you want keep run-on-main-thread as false, change the following function in scanner.js 
```
exports.resume = function(opt) {
    whichCam = opt;
    scannerView.stopCamera();
    //scannerView.resumeCameraPreview(resHandler);
    scannerView.setResultHandler(resHandler);
    scannerView.startCamera(whichCam);
    isRunning = true;
}
```

**Comment by chrystoffer** [comment]
If you want keep run-on-main-thread as false, change the following function in scanner.js
```
exports.resume = function(opt) {
    whichCam = opt;
    scannerView.stopCamera();
    //scannerView.resumeCameraPreview(resHandler);
    scannerView.setResultHandler(resHandler);
    scannerView.startCamera(whichCam);
    isRunning = true;
}
```
